// Second compiler (§5.3.2) — deliberately structurally different from Claude's
// allowlist to stress-test the CapabilityReport abstraction. Gemini CLI's
// permission model is per-activation user consent + a tiered Policy Engine:
// an extension can ship real `policies/*.toml` rules restricting what it may
// even ask for, but it can never self-approve — every activation still
// prompts. That split is exactly the enforce/advise line drawn in supports().
import { join } from "node:path";
import {
  manualEditWarning,
  mirrorResources,
  skippedPath,
  writeFrontmatterFile,
  writeManagedFile,
  parseSkillDirectory,
} from "./sdk.ts";
import type {
  CapabilityReport,
  CompileContext,
  CompileResult,
  DetectedSkill,
  IstaCompiler,
  ResolvedSkill,
  ValidationIssue,
} from "./types.ts";

function policiesToml(skill: ResolvedSkill): string {
  const c = skill.capabilities;
  const tools = c.tools.map((t) => `"${t}"`).join(", ");
  return [
    `# Generated by Ista from skill '${skill.name}' v${skill.version}. Do not edit directly.`,
    `# Gemini's Policy Engine can restrict access to at most what's declared here;`,
    `# it can never self-approve -- every activation still prompts for user consent.`,
    `[capabilities]`,
    `reads_files = ${c.reads_files}`,
    `writes_files = ${c.writes_files}`,
    `network = ${c.network}`,
    `shell_exec = ${c.shell_exec}`,
    `tools = [${tools}]`,
    `spawn_subagents = ${c.spawn_subagents}`,
    "",
  ].join("\n");
}

export const geminiCompiler: IstaCompiler = {
  id: "gemini",
  displayName: "Gemini CLI",

  compile(skill: ResolvedSkill, ctx: CompileContext): CompileResult {
    const overrides = (skill.systems.gemini?.overrides ?? {}) as Record<string, unknown>;
    const frontmatter: Record<string, unknown> = { name: skill.name, description: skill.description, ...overrides };
    const body = [skill.bodyContent, ...skill.attachmentContents.map((a) => a.content)].join("\n\n");

    const targetDir = join(ctx.projectRoot, ".gemini", "skills", skill.name);
    const skillPath = join(targetDir, "SKILL.md");
    const policyPath = join(targetDir, "policies", `${skill.name}.toml`);

    const skillOutcome = writeFrontmatterFile(ctx.projectRoot, skillPath, frontmatter, body, { force: ctx.force });
    const policyOutcome = writeManagedFile(ctx.projectRoot, policyPath, policiesToml(skill), { force: ctx.force });

    const warnings = [manualEditWarning(skillPath, skillOutcome), manualEditWarning(policyPath, policyOutcome)].filter(
      (w): w is string => w !== null,
    );

    const filesWritten: string[] = [];
    if (skillOutcome.written) filesWritten.push(skillPath, ...mirrorResources(skill, targetDir));
    if (policyOutcome.written) filesWritten.push(policyPath);

    const skipped = [skippedPath(skillPath, skillOutcome), skippedPath(policyPath, policyOutcome)].filter(
      (p): p is string => p !== null,
    );

    return { filesWritten, skipped, warnings };
  },

  parse(targetPath: string): DetectedSkill[] {
    return parseSkillDirectory(targetPath);
  },

  supports(): CapabilityReport {
    return {
      // The Policy Engine genuinely restricts what a skill may request —
      // declaring a capability false really does keep it out of scope.
      reads_files: "enforce",
      writes_files: "enforce",
      network: "enforce",
      shell_exec: "enforce",
      tools: "enforce",
      spawn_subagents: "enforce",
      // But nothing here can ever skip the per-activation consent prompt.
      approval: "advise",
    };
  },

  validate(skill: ResolvedSkill): ValidationIssue[] {
    const issues: ValidationIssue[] = [];
    if (skill.capabilities.approval === "auto") {
      issues.push({
        level: "warning",
        message: `capabilities.approval="auto" was requested, but Gemini always requires per-activation user consent -- this cannot be silent.`,
      });
    }
    return issues;
  },
};
